import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { slugify, publicImage, uploadCategoryCover } from './helpers'

function SettingEditor({ type, item, onClose, onSave }) {
  const [form, setForm] = useState(item || { name: '', description: '', status: 'draft', launch_date: '' }); const [message, setMessage] = useState(''); const isCollection = type === 'collections'; const [coverFile, setCoverFile] = useState(null); const [saving, setSaving] = useState(false)
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(e) { e.preventDefault(); setSaving(true); setMessage(''); let payload = { ...form, slug: form.slug || slugify(form.name) }; if (!isCollection) delete payload.launch_date; try { if (coverFile && !isCollection) { const coverPath = await uploadCategoryCover(coverFile, item?.id); payload.image_path = coverPath } const query = item ? supabase.from(type).update(payload).eq('id', item.id) : supabase.from(type).insert(payload); const { error } = await query; if (error) throw error; onSave() } catch (err) { setMessage(err.message) } finally { setSaving(false) } }
  return <div className="modal-backdrop"><form className="modal editor-modal" onSubmit={submit}><div className="modal-header"><h2>{item ? 'Editar' : 'Nova'} {isCollection ? 'coleção' : 'categoria'}</h2><button type="button" className="close-button" onClick={onClose}>×</button></div><div className="form-grid"><label>Nome<input value={form.name || ''} onChange={(e) => change('name', e.target.value)} required /></label><label>Slug<input value={form.slug || ''} onChange={(e) => change('slug', e.target.value)} placeholder="gerado automaticamente" /></label>{isCollection && <label>Data de lançamento<input type="date" value={form.launch_date || ''} onChange={(e) => change('launch_date', e.target.value)} /></label>}<label>Status<select value={form.status || 'draft'} onChange={(e) => change('status', e.target.value)}><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="archived">Arquivado</option></select></label><label className="full">Descrição<textarea value={form.description || ''} onChange={(e) => change('description', e.target.value)} rows="4" /></label>{!isCollection && <><label>Foto de capa<label className="file-input">Selecionar imagem<input type="file" accept="image/*" onChange={(e) => setCoverFile(e.target.files?.[0])} /><span>{coverFile ? coverFile.name : 'Nenhuma imagem selecionada'}</span></label></label>{form.image_path && !coverFile && <div className="image-preview"><img src={publicImage(form.image_path)} alt="Capa da categoria" /></div>}</>}</div>{message && <p className="form-message error">{message}</p>}<div className="modal-footer"><button type="button" className="admin-button secondary" onClick={onClose}>Cancelar</button><button className="admin-button" disabled={saving}>{saving ? 'Salvando…' : 'Salvar'}</button></div></form></div>
}

export default function CatalogSettings({ type }) {
  const title = type === 'collections' ? 'Coleções' : 'Categorias'; const singular = type === 'collections' ? 'coleção' : 'categoria'; const [items, setItems] = useState([]); const [editor, setEditor] = useState(null); const [search, setSearch] = useState(''); const [error, setError] = useState('')
  async function load() { const { data, error: queryError } = await supabase.from(type).select(type === 'collections' ? '*, product_collections(count)' : '*').order('created_at', { ascending: false }); if (queryError) setError(queryError.message); else setItems(data || []) }
  useEffect(() => { load() }, [type])
  async function remove(item) { if (!window.confirm(`Excluir ${singular} “${item.name}”? Esta ação não pode ser desfeita.`)) return; const { error: deleteError } = await supabase.from(type).delete().eq('id', item.id); if (deleteError) setError(deleteError.message); else load() }
  const filtered = items.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()))
  return <section className="admin-page"><div className="page-heading"><div><p className="admin-kicker">Catálogo</p><h1>{title}</h1><p>Organize as peças e campanhas da La Belle Vie.</p></div><button className="admin-button" onClick={() => setEditor({})}>Nova {singular}</button></div><div className="admin-panel"><div className="table-toolbar"><input placeholder={`Buscar ${title.toLowerCase()}`} value={search} onChange={(e) => setSearch(e.target.value)} /></div>{error && <p className="form-message error">{error}</p>}<div className="data-table"><div className="table-row table-header"><span>Nome</span><span>Status</span><span>{type === 'collections' ? 'Produtos' : 'Slug'}</span><span>Ações</span></div>{filtered.map((item) => <div className="table-row" key={item.id}><strong>{item.name}</strong><span className={`status ${item.status}`}>{item.status}</span><span>{type === 'collections' ? item.product_collections?.[0]?.count ?? 0 : item.slug}</span><span className="row-actions"><button onClick={() => setEditor(item)}>Editar</button><button className="danger" onClick={() => remove(item)}>Excluir</button></span></div>)}{!filtered.length && <div className="empty-state">Nenhuma {singular} encontrada.</div>}</div></div>{editor && <SettingEditor type={type} item={editor.id ? editor : null} onClose={() => setEditor(null)} onSave={() => { setEditor(null); load() }} />}</section>
}
