import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

export default function Dashboard() {
  const [stats, setStats] = useState(null); const [recent, setRecent] = useState([])
  useEffect(() => { async function load() { const [all, published, drafts, soldout, collections, latest] = await Promise.all([supabase.from('products').select('*', { count: 'exact', head: true }), supabase.from('products').select('*', { count: 'exact', head: true }).eq('status', 'published'), supabase.from('products').select('*', { count: 'exact', head: true }).eq('status', 'draft'), supabase.from('products').select('*', { count: 'exact', head: true }).eq('status', 'out_of_stock'), supabase.from('collections').select('*', { count: 'exact', head: true }).neq('status', 'archived'), supabase.from('products').select('id,name,status,created_at').order('created_at', { ascending: false }).limit(6)]); setStats({ total: all.count, published: published.count, drafts: drafts.count, soldout: soldout.count, collections: collections.count }); setRecent(latest.data ?? []) } load() }, [])
  const cards = [['Produtos cadastrados', stats?.total, 'total'], ['Publicados', stats?.published, 'published'], ['Rascunhos', stats?.drafts, 'draft'], ['Esgotados', stats?.soldout, 'empty'], ['Coleções ativas', stats?.collections, 'collection']]
  return <section className="admin-page"><div className="page-heading"><div><p className="admin-kicker">Visão geral</p><h1>Olá, Belle Vie.</h1><p>Acompanhe o catálogo da sua loja.</p></div><div className="page-actions"><Link className="admin-button secondary" to="/admin/colecoes">Nova coleção</Link><Link className="admin-button" to="/admin/produtos?novo=1">Novo produto</Link></div></div><div className="stat-grid">{cards.map(([label, value, tone]) => <div className={`stat-card ${tone}`} key={label}><span>{label}</span><strong>{stats ? value : '—'}</strong></div>)}</div><div className="admin-panel recent-panel"><div className="panel-heading"><div><h2>Adicionados recentemente</h2><p>Últimos produtos incluídos no catálogo.</p></div><Link to="/admin/produtos">Ver todos</Link></div>{recent.length ? <div className="recent-list">{recent.map((item) => <div key={item.id}><strong>{item.name}</strong><span className={`status ${item.status}`}>{item.status}</span><small>{new Date(item.created_at).toLocaleDateString('pt-BR')}</small></div>)}</div> : <div className="empty-state">Ainda não há produtos cadastrados. <Link to="/admin/produtos?novo=1">Criar o primeiro produto</Link></div>}</div></section>
}
